### ISSUE TITLE
LineEdit password delay should be platform specific

### ISSUE THREAD

**Issue by pierrenicolasr** [oclero/qlementine#61]
Hello,

```
    // LineEdit
    case SH_LineEdit_PasswordCharacter:
      return QChar(0x2022).unicode(); // Bullet.
    case SH_LineEdit_PasswordMaskDelay:
      return 200;
```

This hard codes 200 ms delay for the password echo delay, but this is not really the wanted behavior on desktop (or non-touch screen devices) where passcodes don't have to echo typed characters.

It would be better to have a delay only when required.
thanks !

**Comment by oclero** [comment]
Yes you're right. You can make a PR and I'll have a look

**Comment by oclero** [comment]
NB: Qlementine is an opinionated QStyle. I'm OK to set 0. I set 200 because at first I thought it looked good, but actually it's not handy on Desktop to have that feature. Let's set 0.
