### ISSUE TITLE
LineEdit border does not scroll 

### ISSUE THREAD

**Issue by christophe-thiery-fw** [oclero/qlementine#64]
With Qt 6.7.2 on macOS. Click a QLineEdit in a scrollable area and scroll up or down:

https://github.com/user-attachments/assets/15a4efa1-e592-4042-8f67-0ed42bbc984c

**Comment by oclero** [comment]
Merci ! Je vois comment corriger ce problème inhérent à QFocusBorder.

**Comment by oclero** [comment]
I can't reproduce the bug on Windows 11 + Qt 6.8.0

https://github.com/user-attachments/assets/cc60b531-0a42-44ea-95e9-7e1ac0f1794e

**Comment by christophe-thiery-fw** [comment]
Looks like this happens when the `QLineEdit` is placed inside a `QScrollArea` from code after `QFocusFrame::setWidget()` was already done. Qt detects the presence of a parent `QScrollArea` in `QFocusFrame::setWidget()`.

**Comment by oclero** [comment]
The best way to avoid the bug would be to create an event filter on QFocusFrame, and hook on ShowEvent, then see how to trigger the geometry update, maybe by sending a dummy QResizeEvent or something (we have to look at QFocusFrame and see what triggers the geometry update)
